S3LambdaDeploymentBucket: <Bucket>
account_nr: <AccountNumber>
region: eu-west-1

PersistRdsLambda:
  fct_name: PersistOnRdsLambda
  stage: staging
  env_vars:
    host: <somehost.xyz.eu-west-1.rds.amazonaws.com>
    port: 5432
    user: <UserName>
    db_name:  <DbName>
    password: <Password>

StoreS3Lambda:
  fct_name: StoreOnS3Lambda
  stage: staging
  env_vars:
    store_bucket: some_existing_bucket  # replace with your bucket where events should be stored
    s3_key: WebhookEvents

Statemachine:
  name: StoreWebhookEventsSfn
  stage: staging

ApiGateway:
  name: WebhookApiGateway
  stage: staging

ApiLambda:
  fct_name: ApiLambda

